### ISSUE TITLE
Can we rephrase as more  positive benefits?

### ISSUE THREAD

**Issue by jtleek** [jhudsl/ITCR_Documentation_and_Usability#29]
https://github.com/jhudsl/ITCR_Documentation_and_Usability/blob/883dd6d348f6e12938c2b3c2d2ceaba259fc23a7/01-intro.Rmd#L15

Any work out there that shows how much love you will get if you do this?

**Comment by cansavvy** [comment]
It's hard to find more positive stats about documentation -> "love". I redug into the literature yesterday, most of it is either kinda negative or not really applicable to this context. Documentation is hard to get a quantitative measure for, let alone a positive one given the state of usability of many bioinformatics tools out there.
