### ISSUE TITLE
Section 3.3: Adding information about reading patterns

### ISSUE THREAD

**Issue by dvenprasad** [jhudsl/ITCR_Documentation_and_Usability#37]
In the context of documentation, it is going to be text heavy and the amount of visuals they can include is limited, so I think talking about reading patterns and how they can leverage them would be useful. 

The two popular ones are F and Z shaped pattern. F is most common for people scanning large chunks of texts.
Here are the links which talk about it in depth:

https://www.interaction-design.org/literature/article/visual-hierarchy-organizing-content-to-follow-natural-eye-movement-patterns

https://uxplanet.org/f-shaped-pattern-for-reading-content-80af79cd3394

**Comment by cansavvy** [comment]
Awesome! Thanks for these links!
