### ISSUE TITLE
Cheat sheet templates

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/ITCR_Documentation_and_Usability#9]
@carriewright11 brought up the idea of supplying some guidance and templates around creating cheat sheets for tools. People love cheat sheets!

Here I'm posting some cheat sheet template ideas and inspiration I found:

- Templates on Overleaf:
https://www.overleaf.com/gallery/tagged/cheat-sheet

- Programming cheat sheets: https://opensource.com/downloads/cheat-sheets

- Tips for making good cheat sheets http://www.mycheatsheet.org/try-this-best-cheat-sheet-template/ and it has a template with it.

- more templates: https://www.templateroller.com/tags/1366-cheat-sheet/

- This one is more focused on infographics but similar idea: https://blog.hubspot.com/marketing/infographic-layout-cheat-sheet

- For inspiration, RStudio cheat sheets: https://www.rstudio.com/resources/cheatsheets/

**Comment by carriewright11** [comment]
These are great!

**Comment by cansavvy** [comment]
This has been added to the course and the template: https://github.com/jhudsl/itcr-template-documentation
